project_id = "faqrzzodtmsybofakcvv"

[functions.process-clover-payment]
verify_jwt = false

[functions.clover-payment-callback]
verify_jwt = false

[functions.admin-update-user-role]
verify_jwt = true