/**
 * Construction & contractor industry terms for autocomplete suggestions.
 * Sorted alphabetically. Easy to extend — just add new terms to the array.
 */
export const CONSTRUCTION_TERMS: string[] = [
  "ADA compliant",
  "AFCI",
  "aggregate",
  "attic",
  "backsplash",
  "backfill",
  "balance due",
  "baseboard",
  "bathroom remodel",
  "board foot",
  "breaker panel",
  "callback",
  "can light",
  "casing",
  "caulking",
  "change order",
  "cleanout",
  "code compliance",
  "compaction",
  "concrete",
  "concrete pour",
  "conduit",
  "countertop",
  "CPVC",
  "crawl space",
  "crown molding",
  "deck build",
  "demo",
  "demolition",
  "deposit",
  "door replacement",
  "drip edge",
  "drywall",
  "egress window",
  "engineered wood",
  "estimate",
  "fascia",
  "fence repair",
  "fire-rated",
  "flange",
  "flashing",
  "flooring install",
  "footing",
  "foundation",
  "framing",
  "galvanized",
  "GFCI",
  "grout",
  "gutter cleaning",
  "hardwood",
  "HVAC",
  "inspection",
  "insulation",
  "invoice",
  "jamb",
  "joist",
  "kitchen remodel",
  "knockdown",
  "laminate",
  "landscape grading",
  "lien waiver",
  "linear foot",
  "load center",
  "load-bearing",
  "LVP",
  "man-hours",
  "mobilization",
  "mortar",
  "net 30",
  "orange peel",
  "OSB",
  "P-trap",
  "paint exterior",
  "paint interior",
  "payment terms",
  "permit",
  "PEX",
  "plumbing",
  "plywood",
  "popcorn ceiling",
  "powder-coated",
  "power washing",
  "pressure-treated",
  "primed",
  "progress payment",
  "punch list",
  "quarter round",
  "R-value",
  "rafter",
  "rebar",
  "recessed lighting",
  "retainage",
  "ridge vent",
  "romex",
  "roof repair",
  "rough-in",
  "sanded",
  "sconce",
  "scope of work",
  "service call",
  "sheathing",
  "sheetrock",
  "shoe molding",
  "shutoff valve",
  "siding",
  "skim coat",
  "slab",
  "soffit",
  "soffit vent",
  "square footage",
  "stucco",
  "subflooring",
  "textured",
  "thinset",
  "threshold",
  "truss",
  "underlayment",
  "vapor barrier",
  "wainscoting",
  "warranty",
  "weatherstripping",
  "window installation",
];
