import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface ReportEmailRequest {
  email: string;
  reportData: {
    title: string;
    dateRange: string;
    sections: any[];
    summary?: any[];
  };
  filters: any;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email, reportData, filters }: ReportEmailRequest = await req.json();

    console.log("Sending report email to:", email);

    // Generate HTML for summary
    let summaryHtml = "";
    if (reportData.summary && reportData.summary.length > 0) {
      summaryHtml = `
        <h2 style="color: #333; margin-top: 20px;">Summary</h2>
        <table style="width: 100%; border-collapse: collapse; margin: 10px 0;">
          <thead>
            <tr style="background-color: #f4f4f4;">
              <th style="padding: 10px; text-align: left; border: 1px solid #ddd;">Metric</th>
              <th style="padding: 10px; text-align: right; border: 1px solid #ddd;">Value</th>
            </tr>
          </thead>
          <tbody>
            ${reportData.summary.map(item => `
              <tr>
                <td style="padding: 10px; border: 1px solid #ddd;">${item.label}</td>
                <td style="padding: 10px; text-align: right; border: 1px solid #ddd;">${item.value}</td>
              </tr>
            `).join("")}
          </tbody>
        </table>
      `;
    }

    // Generate HTML for sections
    const sectionsHtml = reportData.sections.map(section => {
      if (section.data.length === 0) return "";
      
      const columns = section.columns || Object.keys(section.data[0]);
      return `
        <h2 style="color: #333; margin-top: 20px;">${section.title}</h2>
        <table style="width: 100%; border-collapse: collapse; margin: 10px 0;">
          <thead>
            <tr style="background-color: #f4f4f4;">
              ${columns.map(col => `<th style="padding: 10px; text-align: left; border: 1px solid #ddd;">${col}</th>`).join("")}
            </tr>
          </thead>
          <tbody>
            ${section.data.slice(0, 10).map(row => `
              <tr>
                ${columns.map(col => `<td style="padding: 10px; border: 1px solid #ddd;">${row[col] ?? ""}</td>`).join("")}
              </tr>
            `).join("")}
          </tbody>
        </table>
        ${section.data.length > 10 ? `<p style="color: #666; font-style: italic;">Showing 10 of ${section.data.length} rows</p>` : ""}
      `;
    }).join("");

    const emailHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px;">
            ${reportData.title}
          </h1>
          <p style="color: #666; margin: 10px 0;">
            <strong>Period:</strong> ${reportData.dateRange}
          </p>
          
          ${summaryHtml}
          ${sectionsHtml}
          
          <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
          <p style="color: #666; font-size: 12px;">
            This report was generated by CT1 Contractor Hub. For the full interactive report, please log in to your account.
          </p>
        </body>
      </html>
    `;

    const emailResponse = await resend.emails.send({
      from: Deno.env.get("EMAIL_FROM") || "CT1 Reports <onboarding@resend.dev>",
      to: [email],
      subject: `${reportData.title} - ${reportData.dateRange}`,
      html: emailHtml,
    });

    console.log("Email sent successfully:", emailResponse);

    return new Response(JSON.stringify({ success: true, data: emailResponse }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error sending report email:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);