// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqgbohsyggzxwyhwrbjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxZ2JvaHN5Z2d6eHd5aHdyYmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTUxOTksImV4cCI6MjA3Mzg3MTE5OX0.afE03VUVACB98j7_VyhrdloYdk8Nr6VJYV79_NEclck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});